# Generated by Django 5.2.4 on 2025-08-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_chaivarity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='price',
            field=models.TextField(default=0),
        ),
    ]
